// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: socket-svr.proto

package go_micro_chat_socket_service_socketsvr

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SocketSvr service

func NewSocketSvrEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SocketSvr service

type SocketSvrService interface {
	Send(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type socketSvrService struct {
	c    client.Client
	name string
}

func NewSocketSvrService(name string, c client.Client) SocketSvrService {
	return &socketSvrService{
		c:    c,
		name: name,
	}
}

func (c *socketSvrService) Send(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SocketSvr.Send", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SocketSvr service

type SocketSvrHandler interface {
	Send(context.Context, *Request, *Response) error
}

func RegisterSocketSvrHandler(s server.Server, hdlr SocketSvrHandler, opts ...server.HandlerOption) error {
	type socketSvr interface {
		Send(ctx context.Context, in *Request, out *Response) error
	}
	type SocketSvr struct {
		socketSvr
	}
	h := &socketSvrHandler{hdlr}
	return s.Handle(s.NewHandler(&SocketSvr{h}, opts...))
}

type socketSvrHandler struct {
	SocketSvrHandler
}

func (h *socketSvrHandler) Send(ctx context.Context, in *Request, out *Response) error {
	return h.SocketSvrHandler.Send(ctx, in, out)
}
